### PR TITLE
feat(rules): add lines-around-comment rule

### LINKED ISSUE #5: Require Empty Lines Before Comments
I'm tired of seeing

```javascript
it('should look awkward', function() {
  // given
  var foo = 'foo';

  // when
  foo = 42;

  // then
  expect(foo).to.equal(42);
});

```

Empty lines before a comment should be required. See https://eslint.org/docs/rules/lines-around-comment.

### PR DESCRIPTION
**Pull request by philippfromme**
Closes #5

### CODE REVIEW

**Comment by barmac** [comment]
Sir,

```
Error: es5/.eslintrc » plugin:bpmn-io/es5 » plugin:bpmn-io/recommended:
	Configuration for rule "lines-around-comment" is invalid:
	Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '{ beforeBlockComment: true, beforeLineComment: true }').
```

**Review by nikku — CHANGES_REQUESTED** [review]
Please fix and provide test cases that verify the code style @ work.

**Comment by philippfromme** [comment]
> Please fix and provide test cases that verify the code style @ work.

Will do.

**Review by nikku — APPROVED** [review]

**Comment by nikku** [comment]
Released with `v0.9.0`. :tada: integrating it into our tools :1st_place_medal:.

**Pull request merged**
